import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import updates from '../updates.cjs';const {createUpdateService,downloadAsset,ENDPOINT}=updates;
const release=version=>({tag_name:'v'+version,html_url:`https://github.com/Gary06868/QuietField/releases/tag/v${version}`,draft:false,prerelease:false,body:'Changes',assets:[{name:`QuietField-${version}-Windows-x64-public.zip`,browser_download_url:`https://github.com/Gary06868/QuietField/releases/download/v${version}/QuietField-${version}-Windows-x64-public.zip`,size:10,digest:'sha256:'+'a'.repeat(64),state:'uploaded'}]});
async function settings(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'qf-update-test-'));return path.join(dir,'settings.json');}
test('reading a version clears dot persistently, next version becomes unread, upgraded version disappears',async()=>{const prefsPath=await settings();let clock=2000000000,calls=0,next='1.7.0';const opts={version:'1.6.1',prefsPath,now:()=>clock,fetcher:async()=>{calls++;return release(next);}};let svc=await createUpdateService(opts);await svc.check();assert.equal(calls,1);assert.equal(svc.snapshot().unread,true);await svc.read();assert.equal(svc.snapshot().unread,false);svc.close();svc=await createUpdateService(opts);assert.equal(svc.snapshot().latest.version,'1.7.0');assert.equal(svc.snapshot().unread,false);await svc.check();assert.equal(calls,1);next='1.7.1';clock+=86400001;await svc.check();assert.equal(svc.snapshot().unread,true);await svc.read();svc.close();svc=await createUpdateService({...opts,version:'1.7.1'});assert.equal(svc.snapshot().latest,null);assert.equal(svc.snapshot().unread,false);svc.close();});
test('automatic checks can be disabled; manual check still works; requests coalesce',async()=>{const prefsPath=await settings();let calls=0,resolve;const svc=await createUpdateService({version:'1.6.1',prefsPath,fetcher:()=>{calls++;return new Promise(r=>resolve=r);}});await svc.setAuto(false);await svc.check();assert.equal(calls,0);const a=svc.check(true);await new Promise(r=>setImmediate(r));const b=svc.check(true);resolve(release('1.7.0'));await Promise.all([a,b]);assert.equal(calls,1);svc.close();const restored=await createUpdateService({version:'1.6.1',prefsPath});assert.equal(restored.snapshot().autoCheck,false);restored.close();});
test('offline failure retains cached message and next manual attempt works after synchronous transport failure',async()=>{const prefsPath=await settings();let fail=false,calls=0;const svc=await createUpdateService({version:'1.6.1',prefsPath,fetcher:()=>{calls++;if(fail)throw Error('offline');return release('1.7.0');}});await svc.check(true);fail=true;await svc.check(true);assert.equal(svc.snapshot().error,'network');assert.equal(svc.snapshot().latest.version,'1.7.0');await svc.check();assert.equal(calls,2);fail=false;await svc.check(true);assert.equal(calls,3);assert.equal(svc.snapshot().phase,'available');svc.close();});
test('repeated install clicks start only one operation and mark notification read',async()=>{const prefsPath=await settings();let installs=0,resolve;const svc=await createUpdateService({version:'1.6.1',prefsPath,canInstall:true,fetcher:async()=>release('1.7.0'),installer:()=>{installs++;return new Promise(r=>resolve=r);}});await svc.check(true);const first=svc.install(),second=svc.install();while(!resolve)await new Promise(r=>setImmediate(r));assert.equal(installs,1);assert.equal(svc.snapshot().unread,false);resolve();await Promise.all([first,second]);svc.close();});
test('download size and SHA256 are verified; corrupt partial file is removed',async()=>{const prefsPath=await settings(),dir=path.dirname(prefsPath),original=globalThis.fetch,data=Buffer.from('a real ZIP would go here');const asset={url:'https://github.com/Gary06868/QuietField/releases/download/v1.7.0/QuietField-1.7.0-Windows-x64-public.zip',size:data.length,sha256:createHash('sha256').update(data).digest('hex')};globalThis.fetch=async()=>new Response(data);try{await downloadAsset(asset,path.join(dir,'good.zip'),new AbortController().signal);assert.deepEqual(await fs.readFile(path.join(dir,'good.zip')),data);await assert.rejects(downloadAsset({...asset,sha256:'f'.repeat(64)},path.join(dir,'bad.zip'),new AbortController().signal),{code:'checksum'});await assert.rejects(fs.stat(path.join(dir,'bad.zip')),{code:'ENOENT'});}finally{globalThis.fetch=original;}});
