import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'test-results/updates');await fs.mkdir(out,{recursive:true});const profile=path.join(out,'profile-'+Date.now());await fs.mkdir(profile,{recursive:true});
const release=version=>({tag_name:'v'+version,html_url:`https://github.com/Gary06868/QuietField/releases/tag/v${version}`,draft:false,prerelease:false,body:'新版本：更多声音与体验优化。',assets:[]});
await fs.writeFile(path.join(profile,'update-settings.json'),JSON.stringify({autoCheck:true,lastCheck:Date.now(),release:release('1.7.0')}));
const env={...process.env,QUIET_FIELD_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const exe=process.argv[2];let app=await electron.launch({...(exe?{executablePath:exe}:{}),args:exe?[]:[root],env,timeout:60000});const checks=[];
try{let page=await app.firstWindow();await page.evaluate(()=>localStorage.setItem('quiet-field-settings',JSON.stringify({locale:'zh-CN',mix:{'brown-noise':.5},favorites:['brown-noise'],saved:[{id:'qf-test',name:'我的宁静',mix:{'brown-noise':.5}}]})));await page.reload();await page.getByRole('heading',{name:'今天，听见宁静。'}).waitFor();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.webContents.setAudioMuted(true);w.setBounds({x:35,y:35,width:1180,height:760});w.showInactive();});
 await page.locator('.update-unread').waitFor();assert.equal(await page.locator('dialog[open]').count(),0);checks.push('new release has unread dot without popup');
 await page.locator('.updates-entry').click();await page.getByRole('heading',{name:'消息与更新'}).waitFor();await page.waitForFunction(()=>!document.querySelector('.update-unread'));assert.ok((await page.locator('.updates-dialog').innerText()).includes('1.7.0'));await page.screenshot({path:path.join(out,'message-center.png')});await page.getByRole('button',{name:'关闭消息'}).click();
 await app.close();app=await electron.launch({...(exe?{executablePath:exe}:{}),args:exe?[]:[root],env,timeout:60000});page=await app.firstWindow();await page.getByRole('heading',{name:'今天，听见宁静。'}).waitFor();assert.equal(await page.locator('.update-unread').count(),0);assert.equal(await page.locator('dialog[open]').count(),0);checks.push('read state survives process restart with no repeated prompt');
 await app.evaluate((_electron,data)=>{globalThis.fetch=async()=>new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json'}});},release('1.7.1'));
 await page.evaluate(()=>window.desktop.updatesAction('check'));await page.locator('.update-unread').waitFor();assert.equal(await page.locator('dialog[open]').count(),0);checks.push('next version creates one new unread message');
 await page.locator('.updates-entry').click();await page.waitForFunction(()=>!document.querySelector('.update-unread'));await page.getByRole('checkbox',{name:'自动检查新版'}).uncheck();assert.equal((await page.evaluate(()=>window.desktop.updatesState())).autoCheck,false);
 await app.evaluate(()=>{globalThis.fetch=async()=>{throw new Error('offline');};});await page.getByRole('button',{name:'检查更新',exact:true}).click();await page.getByText('暂时连不上 GitHub，请稍后重试。声音播放不受影响。',{exact:true}).waitFor();assert.ok((await page.locator('.updates-dialog').innerText()).includes('1.7.1'));await page.getByRole('button',{name:'关闭消息'}).click();
 const prefs=await page.evaluate(()=>JSON.parse(localStorage.getItem('quiet-field-settings')));assert.equal(prefs.saved[0].name,'我的宁静');assert.equal(prefs.mix['brown-noise'],.5);checks.push('disabled checks and offline errors preserve message, mixes and audio preferences');
 await page.getByRole('button',{name:'EN',exact:true}).click();await page.locator('.updates-entry').click();await page.getByRole('heading',{name:'Messages & updates'}).waitFor();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('bilingual message center fits small displays');
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({passed:true,checks},null,2));console.log('PASS',JSON.stringify(checks));
}finally{await app.close();}
