import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'test-results');await fs.mkdir(out,{recursive:true});const env={...process.env,QUIET_FIELD_TEST_DATA:path.join(out,'i18n-'+Date.now())};delete env.ELECTRON_RUN_AS_NODE;
const exe=process.argv[2],app=await electron.launch({...(exe?{executablePath:exe}:{}),args:exe?[]:[root],env,timeout:60000});
try{
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setAudioMuted(true));
 await page.context().addInitScript(()=>{Object.defineProperty(navigator,'languages',{get:()=>['en-US']});const Original=window.AudioContext;window.__audio={contexts:[],sources:[]};window.AudioContext=class extends Original{constructor(...a){super(...a);window.__audio.contexts.push(this);}createBufferSource(){const s=super.createBufferSource();window.__audio.sources.push(s);return s;}};});
 await page.evaluate(()=>localStorage.removeItem('quiet-field-settings'));await page.reload();await page.getByRole('heading',{name:'Find your quiet.',exact:true}).waitFor();await page.context().setOffline(true);
 assert.equal(await page.locator('.sound-card').count(),53);assert.equal(await page.locator('html').getAttribute('lang'),'en');
 const chinese=await page.locator('body').innerText();assert.ok(!/[\u4e00-\u9fff]/.test(chinese.replace('中文','')),chinese);
 await page.getByRole('textbox',{name:'Search sounds',exact:true}).fill('猫咪');assert.equal(await page.locator('.sound-card').count(),1);await page.getByRole('button',{name:'Play Cat purring',exact:true}).waitFor();await page.getByRole('button',{name:'Clear search',exact:true}).click();
 await page.getByRole('button',{name:'Play Light rain',exact:true}).click();await page.waitForFunction(()=>window.__audio.sources.some(s=>s.buffer&&s.loop));await page.evaluate(()=>{window.__sourceBefore=window.__audio.sources[0];window.__timeBefore=window.__audio.contexts[0].currentTime;});
 await page.getByRole('button',{name:'中文',exact:true}).click();await page.getByRole('heading',{name:'今天，听见宁静。'}).waitFor();await page.getByRole('slider',{name:'混音 小雨音量',exact:true}).fill('175');await page.waitForTimeout(400);
 assert.ok(await page.evaluate(()=>window.__audio.sources.length===1&&window.__audio.sources[0]===window.__sourceBefore&&window.__audio.contexts[0].currentTime>window.__timeBefore));
 await page.getByRole('button',{name:'EN',exact:true}).click();assert.equal(await page.getByRole('slider',{name:'Mix Light rain volume',exact:true}).inputValue(),'175');assert.equal(await page.getByRole('button',{name:'Pause all',exact:true}).count(),1);
 await page.getByRole('button',{name:'Save mix',exact:true}).click();await page.getByLabel('Name your mix').fill('雨夜 / My mix');await page.getByRole('dialog').getByRole('button',{name:'Save mix',exact:true}).click();
 await page.getByRole('button',{name:'Favorite Light rain',exact:true}).click();await page.getByRole('button',{name:'My mixes',exact:true}).click();await page.getByRole('heading',{name:'雨夜 / My mix',exact:true}).waitFor();await page.getByRole('button',{name:'All sounds',exact:true}).click();
 await page.getByRole('button',{name:'Cave water ambience details',exact:true}).click();assert.ok((await page.getByRole('dialog').innerText()).includes('not a field recording'));await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'About & sound credits',exact:true}).click();assert.ok(!/[\u4e00-\u9fff]/.test(await page.getByRole('dialog').innerText()));await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.reload();await page.getByRole('heading',{name:'Find your quiet.'}).waitFor();assert.equal(await page.getByRole('slider',{name:'Mix Light rain volume',exact:true}).inputValue(),'175');await page.getByRole('button',{name:'My mixes',exact:true}).click();await page.getByRole('heading',{name:'雨夜 / My mix',exact:true}).waitFor();await page.getByRole('button',{name:'All sounds',exact:true}).click();
 await page.getByRole('button',{name:'Ocean escape',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.mix-track').length===2&&![...document.querySelectorAll('.mix-name')].some(e=>e.textContent.includes('Loading')));
 await fs.mkdir('docs/images',{recursive:true});for(const [locale,width,height] of [['en',1536,1000],['en',1180,660],['en',390,844],['zh-CN',1536,1000]]){
  await page.getByRole('button',{name:locale==='en'?'EN':'中文',exact:true}).click();await page.setViewportSize({width,height});await page.evaluate(()=>{document.querySelector('main').scrollTo({top:0,behavior:'instant'});return document.fonts.ready;});await page.waitForTimeout(300);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),locale+' horizontal overflow');await page.screenshot({path:width===1536?`docs/images/desktop-${locale}.png`:path.join(out,`i18n-${width}.png`),scale:'css'});
 }
 await page.reload();await page.getByRole('heading',{name:'今天，听见宁静。'}).waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');assert.deepEqual(errors,[]);
 await fs.writeFile(path.join(out,'i18n-results.json'),JSON.stringify({passed:true,systemEnglishDetected:true,explicitChinesePersisted:true,englishPersisted:true,bilingualSearch:true,switchKeepsSourceAndPlayback:true,volumePreserved:true,userMixNameUntouched:true,favoritesAndMixPreserved:true,allPublicNamesTranslated:true,aboutAndNotesTranslated:true,offline:true,widths:[1536,1180,390],errors},null,2));console.log('PASS bilingual UI, offline switching without audio restart, search, persistence, user mixes and 3 widths');
}finally{await app.close();}
