import React,{useEffect,useRef,useState} from 'react';
import {Bell,Download,RefreshCw,Check,X,ExternalLink,LoaderCircle} from 'lucide-react';
import {useLocale} from './LocaleContext.jsx';
import './updates.css';
const copies={
 'zh-CN':{messages:'消息',unread:'有一条未读消息',title:'消息与更新',close:'关闭消息',version:'当前版本',available:'静野有新版了',read:'已读',update:'立即更新',release:'查看发布说明',none:'暂时没有新消息',current:'未发现可用的新版本。',intro:'新版会静静留在这里，不打断你的声音。',auto:'自动检查新版',privacy:'每天最多自动连接 GitHub 检查一次。不会上传音频或使用记录。',check:'检查更新',checking:'正在检查…',downloading:'正在下载更新',preparing:'正在校验和准备更新',installing:'即将重启进入新版',keep:'下载期间可以继续听，完成后会自动重启。收藏、声音组合与导入音频会保留。',cancel:'取消下载',manual:'这个版本暂不能在应用内安装，可以到发布页下载。',again:'重试更新',errors:{network:'暂时连不上 GitHub，请稍后重试。声音播放不受影响。','rate-limited':'GitHub 暂时限制了检查次数，请稍后重试。',checksum:'更新包校验未通过，已停止更新。当前版本保持可用。',prepare:'更新准备未完成。请检查磁盘空间和文件夹权限后重试。',install:'更新程序未能启动，当前版本保持可用。','not-writable':'当前程序文件夹不可写，请移到有写入权限的位置后更新。','unsupported-location':'这个位置不支持直接更新，请从发布页下载。','disk-space':'可用磁盘空间不足，请腾出空间后重试。',settings:'更新偏好暂时无法保存，请检查磁盘权限。'}},
 en:{messages:'Messages',unread:'One unread message',title:'Messages & updates',close:'Close messages',version:'Current version',available:'A new Quiet Field is available',read:'Read',update:'Update now',release:'Release notes',none:'No new messages',current:'No newer release is available.',intro:'New versions wait here without interrupting your sound.',auto:'Check for updates automatically',privacy:'Connects to GitHub at most once a day. No audio or usage history is uploaded.',check:'Check for updates',checking:'Checking…',downloading:'Downloading update',preparing:'Verifying and preparing update',installing:'Restarting into the new version',keep:'Keep listening while it downloads. The app restarts when ready. Favorites, mixes and imported audio stay with you.',cancel:'Cancel download',manual:'In-app installation is unavailable for this release. Download it from the release page.',again:'Retry update',errors:{network:'Cannot reach GitHub right now. Try again later; playback is unaffected.','rate-limited':'GitHub has temporarily limited update checks. Please try later.',checksum:'The update checksum did not match. Your current version is unchanged.',prepare:'Update preparation failed. Check free disk space and folder permissions.',install:'The update helper could not start. Your current version is still available.','not-writable':'The application folder is not writable. Move it to a writable location first.','unsupported-location':'Direct updates are not supported in this location. Use the release page.','disk-space':'There is not enough free disk space for this update.',settings:'Update preferences could not be saved. Check disk permissions.'}}
};
export function UpdateCenter(){
 const {locale}=useLocale(),text=copies[locale==='en'?'en':'zh-CN'];const [state,setState]=useState(null),[open,setOpen]=useState(false);const dialog=useRef();
 useEffect(()=>{let live=true;const off=window.desktop.onUpdatesState(value=>{if(live)setState(value);});window.desktop.updatesState().then(value=>{if(live)setState(value);}).catch(()=>{});window.desktop.updatesReady();return()=>{live=false;off?.();};},[]);
 useEffect(()=>{if(open){dialog.current.showModal();}else dialog.current?.close();},[open]);
 useEffect(()=>{if(open&&state?.unread)window.desktop.updatesAction('read').catch(()=>{});},[open,state?.unread,state?.latest?.version]);
 const action=(name,value)=>window.desktop.updatesAction(name,value).catch(()=>setState(s=>({...s,error:'network'})));
 const busy=['downloading','preparing','installing'].includes(state?.phase),latest=state?.latest;
 return <><button className="updates-entry" aria-label={text.messages+(state?.unread?' · '+text.unread:'')} onClick={()=>setOpen(true)}><Bell size={16}/><span>{text.messages}</span>{state?.unread&&<i className="update-unread" aria-hidden="true"/>}{busy&&<LoaderCircle className="spin" size={13}/>}</button>
 {open&&<dialog className="updates-dialog" ref={dialog} onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===dialog.current)setOpen(false);}}><header><h2>{text.title}</h2><button className="icon-button" aria-label={text.close} onClick={()=>setOpen(false)}><X size={18}/></button></header><p className="update-version">{text.version} {state?.version||'—'}</p>
 {busy?<section className="update-message" role="status"><div className="update-message-title"><LoaderCircle size={22} className="spin"/><h3>{text[state.phase]}</h3></div><p>{latest?.version}</p><progress max="100" value={state.phase==='downloading'?state.progress:undefined}/><p className="update-progress-copy">{state.phase==='downloading'?`${state.progress}% · ${Math.round(state.bytes/1024**2)} / ${Math.round(state.total/1024**2)} MB`:text.keep}</p>{state.phase!=='installing'&&<button className="outline" onClick={()=>action('cancel')}>{text.cancel}</button>}</section>
 :latest?<article className="update-message"><div className="update-message-title"><Download size={22}/><h3>{text.available}</h3><span className="update-read"><Check size={12}/>{text.read}</span></div><strong className="update-release-version">{latest.version}</strong>{latest.notes&&<p className="update-notes">{latest.notes}</p>}<div className="update-actions">{latest.canInstall&&<button className="primary" onClick={()=>action('install')}><Download size={16}/>{state.error?text.again:text.update}</button>}<button className="outline" onClick={()=>action('release')}><ExternalLink size={15}/>{text.release}</button></div><p className="muted">{latest.canInstall?text.keep:text.manual}</p></article>
 :<section className="update-empty"><Bell size={28}/><h3>{text.none}</h3><p>{state?.phase==='current'?text.current:text.intro}</p></section>}
 {state?.error&&<p className="update-error" role="status">{text.errors[state.error]||text.errors.network}</p>}
 <footer className="update-preferences"><label><input type="checkbox" checked={state?.autoCheck!==false} onChange={e=>{const value=e.target.checked;setState(s=>({...s,autoCheck:value}));action('auto',value);}}/><span>{text.auto}</span></label><p className="muted">{text.privacy}</p><button className="outline" disabled={!state||busy||state.phase==='checking'} onClick={()=>action('check')}><RefreshCw size={15} className={state?.phase==='checking'?'spin':''}/>{state?.phase==='checking'?text.checking:text.check}</button></footer>
 </dialog>}</>;
}
